"""Examination domain services."""

from app.modules.examinations.services.details_service import (
    AppointmentIdRequired,
    ExaminationNotFound,
    MissingRequiredFields,
    NoDataProvided,
    delete_examination_details_result,
    get_details_by_appointment_result,
    get_examination_details_result,
    get_examination_id_payload_by_appointment,
    get_psychological_examination_result,
    get_section_details_result,
    load_modal_data_result,
    replace_examination_details,
    save_detail_by_appointment_result,
    save_modal_data_result,
    save_psychological_examination_result,
    save_section_details_result,
)
from app.modules.examinations.services.management_query import (
    ManagementExaminationNotFound,
    get_active_management_examination,
    get_examination_management_detail_result,
    get_examination_management_list_result,
    get_examination_stats_result,
)
from app.modules.examinations.services.status_transition import (
    InvalidStatusTransition,
    InvalidStatusValue,
    StatusTransitionExaminationNotFound,
    complete_psychologist_examination_result,
    confirm_examination_result,
    transfer_to_conclusion_result,
    transfer_to_payment_result,
    update_management_examination_status_result,
)
from app.modules.examinations.services.lookup_service import (
    LookupExaminationNotFound,
    get_examination_doctors_result,
    get_examination_id_by_appointment_result,
    get_examination_packages_result,
    get_examination_services_result,
)
from app.modules.examinations.services.hard_delete_service import (
    HardDeleteExaminationNotFound,
    hard_delete_examination_result,
)
from app.modules.examinations.services.creation_service import (
    CreateExaminationValidationError,
    create_examination_result,
)

__all__ = [
    "AppointmentIdRequired",
    "CreateExaminationValidationError",
    "ExaminationNotFound",
    "HardDeleteExaminationNotFound",
    "InvalidStatusTransition",
    "InvalidStatusValue",
    "LookupExaminationNotFound",
    "ManagementExaminationNotFound",
    "MissingRequiredFields",
    "NoDataProvided",
    "StatusTransitionExaminationNotFound",
    "complete_psychologist_examination_result",
    "confirm_examination_result",
    "create_examination_result",
    "delete_examination_details_result",
    "get_active_management_examination",
    "get_details_by_appointment_result",
    "get_examination_details_result",
    "get_examination_doctors_result",
    "get_examination_id_payload_by_appointment",
    "get_examination_id_by_appointment_result",
    "get_examination_management_detail_result",
    "get_examination_management_list_result",
    "get_examination_packages_result",
    "get_examination_services_result",
    "get_examination_stats_result",
    "get_psychological_examination_result",
    "get_section_details_result",
    "hard_delete_examination_result",
    "load_modal_data_result",
    "replace_examination_details",
    "save_detail_by_appointment_result",
    "save_modal_data_result",
    "save_psychological_examination_result",
    "save_section_details_result",
    "transfer_to_conclusion_result",
    "transfer_to_payment_result",
    "update_management_examination_status_result",
]
